# -*- coding: utf-8 -*-
"""assignment3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZpUg86mttVZ_NvMziFTH9R_Ea0oIwHgY

performing data preprocessing
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Titanic-Dataset.csv")
df.head()

df.shape

df.isnull().any()

df.isnull().sum()

df.columns

df['Age'] = df['Age'].replace(np.NaN,df['Age'].median())
df = df.drop(['Cabin'], axis=1)
df.dropna(subset=['Embarked'],how='any',inplace=True)

df.isnull().any()

df.describe()



corr=df.corr()
corr

sns.heatmap(corr,annot=True)

"""outlayers detection"""

sns.boxplot(df)

fig, ax = plt.subplots(1, 4, figsize=(10, 6))

sns.boxplot(data=df['Age'], ax=ax[0], color='brown')
ax[0].set_xlabel('Age')

sns.boxplot(data=df['SibSp'], ax=ax[1], color='green')
ax[1].set_xlabel('Sibsp')

sns.boxplot(data=df['Parch'], ax=ax[2], color='yellow')
ax[2].set_xlabel('Parch')

sns.boxplot(data=df['Fare'], ax=ax[3], color='blue')
ax[3].set_xlabel('Fare')

from sklearn.preprocessing import LabelEncoder, StandardScaler

# splitting dependent and independent variables
x = df.drop(['Name','SibSp','Parch','Ticket'],axis=1)
y = df['Survived']

encoder = LabelEncoder()
x['Sex'] = encoder.fit_transform(x['Sex'])
x['Embarked'] = encoder.fit_transform(x['Embarked'])

x.head()

scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

"""splitting training and testing data"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_scaled,y,test_size=0.2,random_state=0)

print("Shape of x_train: ",x_train.shape)
print("Shape of x_test: ",x_test.shape)
print("Shape of y_train: ",y_train.shape)
print("Shape of y_test: ",y_test.shape)